
SELECT * FROM EMPLOYEES;

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE UPDATESALARY(
    P_EMPLOYEE_ID IN EMPLOYEES.EMPLOYEEID%TYPE,
    P_PERCENTAGE IN NUMBER
) AS
    V_OLD_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
    -- Fetch the current salary
    SELECT SALARY INTO V_OLD_SALARY
    FROM EMPLOYEES
    WHERE EMPLOYEEID = P_EMPLOYEE_ID;

    -- Update the salary
    UPDATE EMPLOYEES
    SET SALARY = SALARY * (1 + P_PERCENTAGE / 100),
        HIREDATE = SYSDATE
    WHERE EMPLOYEEID = P_EMPLOYEE_ID;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Salary updated successfully.');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Error: Employee ID ' || P_EMPLOYEE_ID || ' does not exist.');
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Salary update failed: ' || SQLERRM);
END UPDATESALARY;
/

EXEC UPDATESALARY(1,5);
EXEC UPDATESALARY(2,3);

SELECT * FROM EMPLOYEES;

